name: marquee_widget
description: "A Flutter widget that scrolls infinitely. Comes with customisation for style, speed, direction, and more. Supports all platforms."
version: 0.0.1
repository: https://github.com/AyushTripathi28/marquee_widget

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
